# Setup
title:               MatthewOdette
tagline:             'A blog'
description:         'Writings on random bits. Usually about a current project or recently solved sticking point.'
url:                 http://matthewodette.com/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matt Odette
  url:               http://matthewodette.com/
  email:             me@matthewodette.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
